### ISSUE TITLE
Mistake?

### ISSUE THREAD

**Issue by Axel-Erfurt** [DEAM0/Windows-7-Activator#4]
Is that intentional? No matter which number you choose, Ultimate is always chosen

shouldn't it be like that?
```
IF %M%==1 GOTO WIN7U
IF %M%==2 GOTO WIN7P
IF %M%==3 GOTO WIN7H
```

**Comment by cyguard2** [comment]
Exactly. Please fix it.

**Comment by DEAM0** [comment]
Fixed, sorry for late update.
